---
title: 
subtitle: 
tags: 
header_img:
leafletmap: true
always_allow_html: yes
last_modified_at: 2022-11-24
output: 
  html_document:
    self_contained: yes
---

```{r setupRMD, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r setup, include=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
library(leaflet)
library(dplyr)
library(knitr)
library(readxl)
library(leaflet.minicharts)
#library(htmltools)

#read_xlsx(paste0('/Users/shane/14Constraint Dropbox/Shane Stoner/IMPRS/Database/ISRaD/LeafletWork', '/ISRaD_database_files/ISRaD_extra_list_v 2.3.6.2022-12-10.xlsx'), sheet = "profile") %>% 
load('/Users/shane/14Constraint Dropbox/Shane Stoner/IMPRS/Database/ISRaD/LeafletWork/ISRaD_database_files/ISRaD_extra_v 2.3.6.2022-12-10.rda')
ISRaD_extra$profile %>% 
  dplyr::select("entry_name", "pro_lat", "pro_long") %>% #glimpse()
  dplyr::distinct() %>%# glimpse()
  dplyr::rename("lat" = "pro_lat") %>% 
  dplyr::rename("lng" = "pro_long") %>%
  dplyr::mutate(entry_name = as.character(entry_name)) %>% 
  dplyr::group_by(entry_name, lat, lng) %>%
  dplyr::mutate(entry_name = ifelse( length(unlist(strsplit(entry_name, "_"))) == 2, 
         paste(unlist(strsplit(entry_name, "_"))[1], "et al.", unlist(strsplit(entry_name, "_"))[2]),
         paste(unlist(strsplit(entry_name, "_"))[1], unlist(strsplit(entry_name, "_"))[2], "et al.", 
               unlist(strsplit(entry_name, "_"))[length(unlist(strsplit(entry_name, "_")))]))) %>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(lng = as.numeric(lng)) %>% 
  dplyr::mutate(lat = as.numeric(lat))-> coordset


m <- leaflet(coordset, width = "80%", height = NULL, options = leafletOptions(zoomSnap = 0.25, zoomDelta=0.25, minZoom = 1.0))
m <- addCircles(m, color = "#8269d7", opacity = 0.7, 
                label = ~htmltools::htmlEscape(entry_name), 
                labelOptions = labelOptions(noHide =FALSE, textOnly = TRUE, textsize = "14px", direction = "bottom", offset = c(0,5)))
m <- addTiles(m)#, options = providerTileOptions(minZoom = 1.0, maxZoom = 4))
m <- setMaxBounds(m, -180, -80, 180, 90)
m <- flyToBounds(m, -160, -60, 160, 70)
m <- setView(m, 0, 28, zoom = 1.25)
m

```

```{r save widget, include=FALSE}

#saveWidget(m, "/Users/shane/14Constraint Dropbox/Shane Stoner/IMPRS/Database/ISRaD/LeafletWork/isradleaflet.html")

```
