#' refs
#'
#' extracts references from dois in the database
#'
#' @param dataset_list ISRaD database as an R list produced by the compile function
#' @param doi vector of digital object identifiers
#' @param style citation syle; apa is used by default
#' @param out type of output generated by the function. Either 'citation' or 'bibtex'.
#' @param return a vector of citations or a list of bibtex entries.
#' @export
#' @import curl
#'

refs <- function(doi, style, out){
  if(out=="citation"){
    all=NULL
    for(i in 1:length(doi)){
      if((!(RCurl::url.exists(paste0("https://www.doi.org/", doi[i]))))){
        entry <- NA
        all=c(all,entry)
      } else {
      x=paste("curl -LH 'Accept: text/x-bibliography; style=", style,"' https://doi.org/", doi[i], sep="")
      entry=system(x, intern=TRUE)
      if (length(entry)!=1) {
        entry <- NA
        all=c(all,entry)
      } else
      print(entry)
      all=c(all,entry[1])
      }
    }
    return(all)}

  if(out=="bibtex"){
    all=NULL
    for(i in 1:length(doi)){
      x=paste("curl -LH 'Accept: application/x-bibtex; style=", style,"' https://doi.org/", doi[i], sep="")
      entry=system(x, intern=TRUE)
      print(entry)
      all=list(all,entry)
    }
    return(all)
  }
  else
    print("Error: out must be 'citation' or 'bibtex' ")

}
