---
title: "ISRaD Credits"
date: \textit{\today}
output:
  md_document:
    variant: gfm
  pdf_document:
    latex_engine: xelatex
  html_document:
csl: apa-7th-edition.csl
bibliography: credits.bib
nocite: '@*'
header_includes:
- \usepackage[utf8]{inputenc}
- \usepackage{float}
- \usepackage{was}
- \usepackage{textcomp}
- \usepackage{upgreek}
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r libs, include = FALSE}
# load libraries
library(curl)
library(dplyr)
library(purrr)
```

```{r refs, include = FALSE}
# Notes:
# 1) Guo_2006 has curly brackets around greek symbols that will cause pandoc error 83
# 2) Lybrand_2017 has curly brackets around greek symbols that will cause pandoc error 83
# Errors 1 & 2 need to be manually edited, or a regex/gsub needs to be written to fix them on the fly
# 3) all "upgreek" symbols fail to render, as do "\mathsemicolon"s

# load ISRaD data
load("../ISRaD_data_files/database/ISRaD_data.rda")

# get DOIs and clean up
dois <- ISRaD_data$metadata$doi
cleandois <- as.character(dois[dois[] != "israd"])

# cf. <ttps://users.aalto.fi/~mkouhia/2016/bibtex-from-dx-doi-org/>
h <- new_handle()
handle_setheaders(h, "accept" = "application/x-bibtex")

# .bib fx
doi.bib <- function(doi, .bib) {
  url <- paste0("https://doi.org/", doi)
  try(
    walk(url, ~ {
      curl(., handle = h) %>%
        readLines(warn = FALSE, encoding = "UTF-8") %>%
        write(file = .bib, append = TRUE)
    }))
}

# remove old .bib
if(file.exists(file.path("./credits.bib"))) {
  file.remove(file.path("./credits.bib"))
}

# generate new .bib
lapply(seq_along(cleandois), function(i) {
  doi.bib(cleandois[i], .bib = "credits.bib")
})

# clean up .bib file
.bib <- readLines("credits.bib")
clean.bib <- gsub("\\{upDelta}", "upDelta", .bib)

# replace upgreek symbols with regular greek symbols
clean.bib <- gsub("upDelta", "Delta", clean.bib)
clean.bib <- gsub("updelta", "delta", clean.bib)

# save
cat(clean.bib, sep = "\n", file = "credits.bib")
```
# Main compilations
ISRaD has been built based on two main compilations: 

* `r {rcrossref::cr_cn("10.1126/science.aad4273", format = "text", style = "apa")}`
* `r {rcrossref::cr_cn("10.1111/gcb.13012", format = "text", style = "apa")}`

# Studies within ISRaD
Currently there are `r {length(dois)}` entries in ISRaD, which are from the following publications:
