#' ISRaD.extra.fill_soilorders
#'
#' @description Fills pro_usda_soil_order field from pro_soil_taxon field.
#' @param database ISRaD dataset object.
#' @export
#' @details This function is a static conversion script written at the Fall 2018 Powell Center workshop and therefore performance is not guaranteed for new entries.
#' @return returns ISRaD_data object with filled pro_usda_soil_order column
#' @details
#' Back fills pro_usda_soil_order based on USDA classifications

ISRaD.extra.fill_soilorders<-function(database){
  
  requireNamespace("plyr")
  
  database$profile$pro_usda_soil_order <- plyr::revalue(database$profile$pro_soil_taxon, c("Abruptic Luvisol" = "Andisols",
                                                                                           "acidic Albic Luvisol" = "Alfisols",
                                                                                           "Acrisol (Humic)" = "Ultisols",
                                                                                           "Acrudoxic Fulvudands" = "Andisols",
                                                                                           "Alf" = "Alfisols",
                                                                                           "Alfisal" = "Alfisols",
                                                                                           "Alfisol" = "Alfisols",
                                                                                           "And" = "Andisols",
                                                                                           "Andic Dystrudept" = "Inceptisols",
                                                                                           "Andic Humitropept" = "Inceptisols",
                                                                                           "Andisol" = "Andisols", 
                                                                                           "Andisol (Hapludand) "= "Andisols",
                                                                                           "Andosol" = "Andisols",
                                                                                           "Aquic Hapludand" = "Andisols",
                                                                                           "Aquic Hydrudand" = "Andisols",
                                                                                           "Ard" = "Aridisols",
                                                                                           "Arenosol (Eutric) " = "Entisols",
                                                                                           "Argiustoll" = "Mollisols",
                                                                                           "Aridisol" = "Aridisols",
                                                                                           "brown earth" = "Inceptisols",
                                                                                           "calacaric Regosol" = "Entisols",
                                                                                           "calcaric Regosol, Arenosol" = "Entisols",
                                                                                           "Calciustoll" = "Mollisols",
                                                                                           "Cambisol" = "Inceptisols",
                                                                                           "Cambisol (Dystric)" = "Inceptisols",
                                                                                           "Chernozem / Kastanozem /Phaeozem" = "Mollisols",
                                                                                           "clayey-skeletal, mixed superactive, mesic Typic Paleustoll" = "Mollisols",
                                                                                           "Coarse-loamy, isotic, frigid Alfic Oxyaquic Haplorthods" = "Spodosols",
                                                                                           "coarse, loamy, isotic, frigid, Typic Haplorthods" = "Spodosols",
                                                                                           "colluvic Luvisol" = "Alfisols",
                                                                                           "colluvic Regosol" = "Entisols",
                                                                                           "Cryosol" = "Gelisols",
                                                                                           "Duric Kastanozem / Duric Chernozem " = "Mollisols",
                                                                                           "Duritorrand" = "Andisols",
                                                                                           "Dystric Cambisoil" = "Inceptisols",
                                                                                           "dystric Cambisol" = "Inceptisols",
                                                                                           "Dystric Cambisol" = "Inceptisols",
                                                                                           "Dystrochrepts" = "Inceptisols",
                                                                                           "Dystrustept" = "Inceptisols",
                                                                                           "Endoaqualf " = "Alfisols",
                                                                                           "Ent" = "Entisols",
                                                                                           "Entic Cyrumbrept" = "Inceptisols",
                                                                                           "Entic Vitrands" = "Andisols",
                                                                                           "Entic Vitrands " = "Andisols",
                                                                                           "Entisol" = "Entisols",
                                                                                           "Ept" = "Inceptisols",
                                                                                           "Ert" = "Vertisols",
                                                                                           "Ferralic Cambisol" = "Inceptisols",
                                                                                           "fine, smectitic, mesic, Aquertic, Chromic Hapludalfs" = "Alfisols",
                                                                                           "Fragiaqualf " = "Alfisols",
                                                                                           "Fulvic Andosol" = "Andisols",
                                                                                           "Gel" = "Gelisols",
                                                                                           "Gelisol" = "Gelisols",
                                                                                           "Gelisols" = "Gelisols",
                                                                                           "Gleysol" = "Inceptisols",
                                                                                           "Gleysol " = "Inceptisols",
                                                                                           "glossalbic Cambisol" = "Inceptisols",
                                                                                           "Haplic Luvisol" = "Alfisols",
                                                                                           "Haplocambid" = "Inceptisols",
                                                                                           "Haplotorrent" = "Entisols",
                                                                                           "Hapludand " = "Andisols",
                                                                                           "Haplustalf" = "Alfisols",
                                                                                           "Haplustert" = "Vertisols",
                                                                                           "Haplustox" = "Oxisols",
                                                                                           "Histels" = "Gelisols",
                                                                                           "Histosol" = "Histosols",
                                                                                           "Histosol & humic gleysol" = "Histosols",
                                                                                           "Humic cambisol" = "Inceptisols",
                                                                                           "Humitropept" = "Inceptisols",
                                                                                           "hydrous, ferrihydritic, Acrudoxic Hydrudands" = "Andisols",
                                                                                           "Hydrous, ferrihydritic, isothermic Acrudoxic Hydrudands?" = "Andisols",
                                                                                           "Inceptic and Aquic Hapludox" = "Oxisols",
                                                                                           "Inceptic Hapludox" = "Oxisols",
                                                                                           "Inceptisol" = "Inceptisols",
                                                                                           "Kastanozem" = "Mollisols",
                                                                                           "Kastanozem/Chernozem" = "Mollisols",
                                                                                           "Leptosol" = "Entisols",
                                                                                           "Lithic Haplustolls" = "Mollisols",
                                                                                           "Lithic Ustorthents" = "Entisols",
                                                                                           "Lithic Ustropept" = "Inceptisols",
                                                                                           "loamy-skeletal, mixed superactive, mesic Typic Ustorthent" = "Entisols",
                                                                                           "loamy Gelisol" = "Gelisols",
                                                                                           "loamy, mixed, superactive, mesic Lithic Argiustoll" = "Mollisols",
                                                                                           "loamy, mixed, superactive, mesic Typic Haplustept" = "Inceptisols",
                                                                                           "Luvic Kastanozem / Luvic Chernozem" = "Mollisols",
                                                                                           "Luvisol" = "Alfisols",
                                                                                           "mesic Typic Paleustoll" = "Mollisols",
                                                                                           "Mollisol "= "Mollisols",
                                                                                           "Mollisols" = "Mollisols",
                                                                                           "Natric haplustalf" = "Alfisols",
                                                                                           "Natrusalf" = "Alfisols",
                                                                                           "Oll" = "Mollisols",
                                                                                           "Ox" = "Oxisols",
                                                                                           "Ox ; Plunthustalf ; Ferrallitic soil, moderately desaturated, impoverished Plunthustalf" = "Alfisols",
                                                                                           "Oxisol" = "Oxisols",
                                                                                           "Oxyaquic Haplustolls" = "Mollisols",
                                                                                           "pachic argixeroll" = "Mollisols",
                                                                                           "Pachic Fulvudands" = "Andisols",
                                                                                           "Pachic Xerumbrept" = "Inceptisols",
                                                                                           "Petric Durisols" = "Aridisols",
                                                                                           "Petroduric Histic Andosol" = "Andisols",
                                                                                           "Plinthic Kandiudox" = "Oxisols",
                                                                                           "Podzol" = "Spodosols",
                                                                                           "sandy, mixed, frigid, Entic and Lamellic Haplorthods," = "Spodosols",
                                                                                           "sandy, skeletal, mixed, mesic, Typic Dystrudepts" = "Inceptisols",
                                                                                           "Sombritropept" = "Inceptisols",
                                                                                           "Spo" = "Spodosols",
                                                                                           "Spodosol" = "Spodosols",
                                                                                           "Thaptic Andosol" = "Andisols",
                                                                                           "Thaptic Udivitrand" = "Andisols",
                                                                                           "thermic Typic Haploxeralf" = "Alfisols",
                                                                                           "thixotropic, isothermic Typic Hydrandepts" = "Inceptisols",
                                                                                           "Typic and Aquic Haplorthods " = "Spodosols",
                                                                                           "typic argixeroll" = "Mollisols",
                                                                                           "Typic Dystrochrept" = "Inceptisols",
                                                                                           "Typic Dystrochrepts" = "Inceptisols",
                                                                                           "Typic Epiaquepts" = "Inceptisols",
                                                                                           "Typic Haplocryept" = "Inceptisols",
                                                                                           "Typic Haplohumults"= "Ultisols",
                                                                                           "Typic Haplorthods" = "Spodosols",
                                                                                           "Typic Haploxerepts " = "Inceptisols",
                                                                                           "Typic Hapludalfs" = "Alfisols",
                                                                                           "Typic haplusterts" = "Vertisols",
                                                                                           "Typic hydrudand" = "Andisols",
                                                                                           "Typic Kandiudults" = "Ultisols",
                                                                                           "Typic Kanhapludults" = "Ultisols",
                                                                                           "Typic Pellustert" = "Vertisols",
                                                                                           "Typic troposamments" = "Entisols",
                                                                                           "Typic Xerocrept" = "Inceptisols",
                                                                                           "Ult" = "Ultisols",
                                                                                           "Ultic Haploxeralf" = "Alfisols",
                                                                                           "Ultic Haploxerolls" = "Mollisols",
                                                                                           "Utisol" = "Ultisols",
                                                                                           "Umbrisol" = "Entisols",
                                                                                           "USDA" = "NA",
                                                                                           "Ustorthent" = "Entisols",
                                                                                           "Utisol" = "Ultisols",
                                                                                           "Vertisol; Argillic Pelludert" = "Vertisols",
                                                                                           "very-fine, mixed, active, frigid Aquic Glossudalfs" = "Alfisols",
                                                                                           "Xerumberpt" = "Inceptisols",
                                                                                           "Xerumbrepts" = "Inceptisols"), warn_missing = F)
  
  return(database)
}
