#' ISRaD.extra.fill_soilorders
#'
#' @description Fills pro_usda_soil_order field from pro_soil_taxon field.
#' @param database ISRaD dataset object.
#' @export
#' @details This function is a static conversion script written at the Fall 2018 Powell Center workshop and therefore performance is not guaranteed for new entries.
#' @import plyr
#' @return returns ISRaD_data object with filled pro_usda_soil_order column

ISRaD.extra.fill_soilorders<-function(database){

  requireNamespace("plyr")

  database$profile$pro_usda_soil_order <- plyr::revalue(database$profile$pro_soil_taxon,
                                              c("Abruptic Luvisol" = "Andisols",
                                                "acidic Albic Luvisol" = "Alfisols",
                                                "Acrisol (Humic)" = "Ultisols",
                                                "Alf" = "Alfisols",
                                                "Alfisal" = "Alfisols",
                                                "And" = "Andisols",
                                                "Andic Dystrudept" = "Inceptisols",
                                                "Andosol" = "Andisols",
                                                "Aquic Hapludand" = "Andisols",
                                                "Aquic Hydrudand" = "Andisols",
                                                "Arenosol (Eutric) " = "Entisols",
                                                "brown earth" = "Inceptisols",
                                                "calacaric Regosol" = "Entisols",
                                                "calcaric Regosol, Arenosol" = "Entisols",
                                                "Cambisol" = "Inceptisols",
                                                "Cambisol (Dystric)" = "Inceptisols",
                                                "Chernozem / Kastanozem /Phaeozem" = "Mollisols",
                                                "clayey-skeletal, mixed superactive, mesic Typic Paleustoll" = "Mollisols",
                                                "colluvic Luvisol" = "Alfisols",
                                                "colluvic Regosol" = "Entisols",
                                                "Cryosol" = "Gelisols",
                                                "Duric Kastanozem / Duric Chernozem " = "Mollisols",
                                                "Dystric Cambisoil" = "Inceptisols",
                                                "dystric Cambisol" = "Inceptisols",
                                                "Endoaqualf " = "Alfisols",
                                                "Ent" = "Entisols",
                                                "Entic Vitrands" = "Andisols",
                                                "Entic Vitrands " = "Andisols",
                                                "Ept" = "Inceptisols",
                                                "Ert" = "Vertisols",
                                                "Fragiaqualf " = "Alfisols",
                                                "Fulvic Andosol" = "Andisols",
                                                "Gel" = "Gelisols",
                                                "Gelisols" = "Gelisols",
                                                "Gleysol" = "Inceptisols",
                                                "Gleysol " = "Inceptisols",
                                                "glossalbic Cambisol" = "Inceptisols",
                                                "Hapludand " = "Andisols",
                                                "Haplustox" = "Oxisols",
                                                "Histels" = "Gelisols",
                                                "Histosol & humic gleysol" = "Histosols",
                                                "Humic cambisol" = "Inceptisols",
                                                "hydrous, ferrihydritic, Acrudoxic Hydrudands" = "Andisols",
                                                "Hydrous, ferrihydritic, isothermic Acrudoxic Hydrudands?" = "Andisols",
                                                "Inceptic and Aquic Hapludox" = "Oxisols",
                                                "Inceptic Hapludox" = "Oxisols",
                                                "Kastanozem" = "Mollisols",
                                                "Kastanozem/Chernozem" = "Mollisols",
                                                "Leptosol" = "Entisols",
                                                "Lithic Haplustolls" = "Mollisols",
                                                "Lithic Ustorthents" = "Entisols",
                                                "Lithic Ustropept" = "Inceptisols",
                                                "loamy Gelisol" = "Gelisols",
                                                "loamy-skeletal, mixed superactive, mesic Typic Ustorthent" = "Entisols",
                                                "loamy, mixed, superactive, mesic Lithic Argiustoll" = "Mollisols",
                                                "loamy, mixed, superactive, mesic Typic Haplustept" = "Inceptisols",
                                                "Luvic Kastanozem / Luvic Chernozem" = "Mollisols",
                                                "Luvisol" = "Alfisols",
                                                "Mollisols" = "Mollisols",
                                                "Oll" = "Mollisols",
                                                "Ox" = "Oxisols",
                                                "Ox ; Plunthustalf ; Ferrallitic soil, moderately desaturated, impoverished Plunthustalf" = "Alfisols",
                                                "Oxyaquic Haplustolls" = "Mollisols",
                                                "pachic argixeroll" = "Mollisols",
                                                "Petric Durisols" = "Aridisols",
                                                "Petroduric Histic Andosol" = "Andisols",
                                                "Plinthic Kandiudox" = "Oxisols",
                                                "Podzol" = "Spodosols",
                                                "Spo" = "Spodosols",
                                                "Thaptic Andosol" = "Andisols",
                                                "Thaptic Udivitrand" = "Andisols",
                                                "thermic Typic Haploxeralf" = "Alfisols",
                                                "thixotropic, isothermic Typic Hydrandepts" = "Inceptisols",
                                                "Typic and Aquic Haplorthods " = "Spodosols",
                                                "typic argixeroll" = "Mollisols",
                                                "Typic Dystrochrept" = "Inceptisols",
                                                "Typic Dystrochrepts" = "Inceptisols",
                                                "Typic Epiaquepts" = "Inceptisols",
                                                "Typic Haplohumults"= "Ultisols",
                                                "Typic Haplorthods" = "Spodosols",
                                                "Typic Haploxerepts " = "Inceptisols",
                                                "Typic Hapludalfs" = "Alfisols",
                                                "Typic Kandiudults" = "Alfisols",
                                                "Typic Pellustert" = "Vertisols",
                                                "Ult" = "Ultisols",
                                                "Ultic Haploxerolls" = "Mollisols",
                                                "Utisol" = "Ultisols",
                                                "Vertisol; Argillic Pelludert" = "Vertisols",
                                                "Xerumbrepts" = "Inceptisols"), warn_missing = F)

  return(database)
}
